/**
 * Phase 10 demo scenario 3: "logo creation" - exercises the Image Agent
 * pipeline (ImageManager -> ImageProvider, primary/fallback chain, usage
 * recording) end to end with a hand-rolled fake ImageProvider, so this needs
 * no real API key and makes no external calls. No existing test in the repo
 * covers src/image/ at all (see docs/AI_MANAGER_ARCHITECTURE_AUDIT.md Phase 8
 * - it shipped without tests), so this establishes the first one, mirroring
 * the LLMProvider mock pattern used for src/llm/manager.ts.
 *
 * Deliberately tests ImageManager directly rather than through the
 * `image_generate` tool (src/actions/tools/image.ts): that tool writes
 * generated bytes to the REAL ~/.jarvis/images directory via writeFileSync
 * with no sandboxing hook, which would pollute the developer's actual home
 * directory on every test run. ImageManager.generate() is the full pipeline
 * the tool itself calls into (provider selection, fallback, retry, usage
 * recording) minus that disk side effect.
 */
import { describe, expect, it, beforeEach } from 'bun:test';
import { initDatabase, getDb } from '../vault/schema.ts';
import { ImageManager } from './manager.ts';
import type { ImageProvider, ImageGenerateOptions, ImageResult } from './provider.ts';
import { queryUsage, setUsageDatabase } from '../llm/usage.ts';

const TINY_PNG_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';

class FakeImageProvider implements ImageProvider {
  constructor(
    public name: string,
    private behavior: 'succeed' | 'always_fail' | { failTimes: number },
  ) {}
  private failuresSoFar = 0;

  async generate(prompt: string, options?: ImageGenerateOptions): Promise<ImageResult> {
    if (this.behavior === 'always_fail') {
      throw new Error(`${this.name}: 500 internal server error`);
    }
    if (typeof this.behavior === 'object' && this.failuresSoFar < this.behavior.failTimes) {
      this.failuresSoFar++;
      throw new Error(`${this.name}: temporarily unavailable`);
    }
    return {
      images: [{ b64: TINY_PNG_B64, media_type: 'image/png', revised_prompt: `${prompt} (revised by ${this.name})` }],
      model: options?.model ?? `${this.name}-default`,
    };
  }

  async listModels(): Promise<string[]> { return [`${this.name}-default`]; }
}

describe('ImageManager end-to-end: logo creation', () => {
  beforeEach(() => {
    initDatabase(':memory:');
    // recordUsage() is a no-op until wired to a DB resolver - production
    // wires this at daemon startup (`() => getDb()`); tests must do the same.
    setUsageDatabase(() => getDb());
  });

  it('generates a logo via the primary provider and records usage', async () => {
    const manager = new ImageManager();
    manager.registerProvider(new FakeImageProvider('openai-image', 'succeed'));

    const result = await manager.generate('A minimalist coffee cup logo, flat design, blue and white', {
      size: '1024x1024',
    });

    expect(result.images).toHaveLength(1);
    expect(result.images[0]!.media_type).toBe('image/png');
    expect(result.images[0]!.revised_prompt).toContain('openai-image');
    expect(result.model).toBe('openai-image-default');

    const usage = queryUsage({ subsystems: ['image'] }, 'provider');
    expect(usage.total.calls).toBe(1);
    expect(usage.total.errors).toBe(0);
  });

  it('falls through the configured chain when the primary provider fails, recording the failed attempt as usage', async () => {
    const manager = new ImageManager();
    manager.registerProvider(new FakeImageProvider('openai-image', 'always_fail'));
    manager.registerProvider(new FakeImageProvider('gemini-image', 'succeed'));
    manager.setFallbackChain(['gemini-image']);

    const result = await manager.generate('A minimalist coffee cup logo');

    expect(result.model).toBe('gemini-image-default');
    const usage = queryUsage({ subsystems: ['image'] }, 'provider');
    // 2 failed attempts on openai-image (MAX_RETRIES_PER_PROVIDER) + 1 success on gemini-image.
    expect(usage.total.calls).toBe(3);
    expect(usage.total.errors).toBe(2);
  });

  it('retries a transiently-failing provider before giving up on the whole chain', async () => {
    const manager = new ImageManager();
    manager.registerProvider(new FakeImageProvider('openai-image', { failTimes: 1 }));

    const result = await manager.generate('A logo that works on the second try');
    expect(result.images).toHaveLength(1);
  });

  it('throws with a clear error when every provider in the chain fails', async () => {
    const manager = new ImageManager();
    manager.registerProvider(new FakeImageProvider('openai-image', 'always_fail'));

    await expect(manager.generate('A logo')).rejects.toThrow(/openai-image.*failed/s);
  });

  it('throws when no providers are configured at all (the API-key-not-set case)', async () => {
    const manager = new ImageManager();
    expect(manager.hasProviders()).toBe(false);
    await expect(manager.generate('A logo')).rejects.toThrow('No image providers configured.');
  });
});
